tabs:
  regional: "RegionalData"
  national: "NationalData"
  subnational: "SubnationalData"
  sources: "Sources"


googlesheets:
  prod: "https://docs.google.com/spreadsheets/d/15vW6LUfAAHLsblWPt2bvZ8WrWTwsqwjdJy09grI3CrM/edit#gid=0"
  scratch: "https://docs.google.com/spreadsheets/d/1kAyXs1UDCPYhOrwcQiXWJ3AReQx8mMFNK5QksXu8r3s/edit#gid=0"

json:
  output: "all.json"

# national
scraper_national:
  population:
    source: "WorldPop"
    source_url: "https://data.humdata.org/search?organization=worldpop&q=%22population%20counts%22"
    url: "https://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=excel&dataformat=list"
    format: "xls"
    sheet: "Data"
    headers: 3
    prefilter: "Value is not None"
    admin:
      - "Country Code"
    date: "Year"
    date_type: "year"
    input:
      - "Value"
    output:
      - "Population"
    output_hxl:
      - "#population"

aggregate_regional:
  "#population":
    action: "sum"
  "#affected+food+ipc+p3plus+num":
    action: "sum"

# subnational
ipc:
  dataset: "ipc-country-data"
  url: "https://api.ipcinfo.org"

scraper_subnational:
  population:
    source: "WorldPop/UNFPA"
    source_url: "https://data.humdata.org/search?organization=worldpop&q=%22population%20counts%22"
    dataset: "population-statistics-for-data-explorers"
    format: "csv"
    admin:
      - "alpha_3"
      - "ADM_PCODE"
    admin_exact: True
    input:
      - "Population"
    transform:
      "Population": "get_numeric_if_possible(Population)"
    output:
      - "Population"
    output_hxl:
      - "#population"

countries:
  - ETH
  - KEN
  - SOM

country_name_overrides:

country_name_mappings:

admin1_info:
  - {country: Ethiopia, iso3: ETH, pcode: ET14, name: Addis Ababa}
  - {country: Ethiopia, iso3: ETH, pcode: ET02, name: Afar}
  - {country: Ethiopia, iso3: ETH, pcode: ET03, name: Amhara}
  - {country: Ethiopia, iso3: ETH, pcode: ET06, name: Benishangul Gumz}
  - {country: Ethiopia, iso3: ETH, pcode: ET15, name: Dire Dawa}
  - {country: Ethiopia, iso3: ETH, pcode: ET12, name: Gambela}
  - {country: Ethiopia, iso3: ETH, pcode: ET13, name: Harari}
  - {country: Ethiopia, iso3: ETH, pcode: ET04, name: Oromia}
  - {country: Ethiopia, iso3: ETH, pcode: ET07, name: SNNP}
  - {country: Ethiopia, iso3: ETH, pcode: ET16, name: Sidama}
  - {country: Ethiopia, iso3: ETH, pcode: ET05, name: Somali}
  - {country: Ethiopia, iso3: ETH, pcode: ET11, name: South West Ethiopia}
  - {country: Ethiopia, iso3: ETH, pcode: ET01, name: Tigray}
  - {country: Kenya, iso3: KEN, pcode: KE030, name: Baringo}
  - {country: Kenya, iso3: KEN, pcode: KE036, name: Bomet}
  - {country: Kenya, iso3: KEN, pcode: KE039, name: Bungoma}
  - {country: Kenya, iso3: KEN, pcode: KE040, name: Busia}
  - {country: Kenya, iso3: KEN, pcode: KE028, name: Elgeyo Marakwet}
  - {country: Kenya, iso3: KEN, pcode: KE014, name: Embu}
  - {country: Kenya, iso3: KEN, pcode: KE007, name: Garissa}
  - {country: Kenya, iso3: KEN, pcode: KE043, name: Homa Bay}
  - {country: Kenya, iso3: KEN, pcode: KE011, name: Isiolo}
  - {country: Kenya, iso3: KEN, pcode: KE034, name: Kajiado}
  - {country: Kenya, iso3: KEN, pcode: KE037, name: Kakamega}
  - {country: Kenya, iso3: KEN, pcode: KE035, name: Kericho}
  - {country: Kenya, iso3: KEN, pcode: KE022, name: Kiambu}
  - {country: Kenya, iso3: KEN, pcode: KE003, name: Kilifi}
  - {country: Kenya, iso3: KEN, pcode: KE020, name: Kirinyaga}
  - {country: Kenya, iso3: KEN, pcode: KE045, name: Kisii}
  - {country: Kenya, iso3: KEN, pcode: KE042, name: Kisumu}
  - {country: Kenya, iso3: KEN, pcode: KE015, name: Kitui}
  - {country: Kenya, iso3: KEN, pcode: KE002, name: Kwale}
  - {country: Kenya, iso3: KEN, pcode: KE031, name: Laikipia}
  - {country: Kenya, iso3: KEN, pcode: KE005, name: Lamu}
  - {country: Kenya, iso3: KEN, pcode: KE016, name: Machakos}
  - {country: Kenya, iso3: KEN, pcode: KE017, name: Makueni}
  - {country: Kenya, iso3: KEN, pcode: KE009, name: Mandera}
  - {country: Kenya, iso3: KEN, pcode: KE010, name: Marsabit}
  - {country: Kenya, iso3: KEN, pcode: KE012, name: Meru}
  - {country: Kenya, iso3: KEN, pcode: KE044, name: Migori}
  - {country: Kenya, iso3: KEN, pcode: KE001, name: Mombasa}
  - {country: Kenya, iso3: KEN, pcode: KE021, name: Muranga}
  - {country: Kenya, iso3: KEN, pcode: KE047, name: Nairobi}
  - {country: Kenya, iso3: KEN, pcode: KE032, name: Nakuru}
  - {country: Kenya, iso3: KEN, pcode: KE029, name: Nandi}
  - {country: Kenya, iso3: KEN, pcode: KE033, name: Narok}
  - {country: Kenya, iso3: KEN, pcode: KE046, name: Nyamira}
  - {country: Kenya, iso3: KEN, pcode: KE018, name: Nyandarua}
  - {country: Kenya, iso3: KEN, pcode: KE019, name: Nyeri}
  - {country: Kenya, iso3: KEN, pcode: KE025, name: Samburu}
  - {country: Kenya, iso3: KEN, pcode: KE041, name: Siaya}
  - {country: Kenya, iso3: KEN, pcode: KE006, name: Taita Taveta}
  - {country: Kenya, iso3: KEN, pcode: KE004, name: Tana River}
  - {country: Kenya, iso3: KEN, pcode: KE013, name: Tharaka Nithi}
  - {country: Kenya, iso3: KEN, pcode: KE026, name: Trans Nzoia}
  - {country: Kenya, iso3: KEN, pcode: KE023, name: Turkana}
  - {country: Kenya, iso3: KEN, pcode: KE027, name: Uasin Gishu}
  - {country: Kenya, iso3: KEN, pcode: KE038, name: Vihiga}
  - {country: Kenya, iso3: KEN, pcode: KE008, name: Wajir}
  - {country: Kenya, iso3: KEN, pcode: KE024, name: West Pokot}
  - {country: Somalia, iso3: SOM, pcode: SO11, name: Awdal}
  - {country: Somalia, iso3: SOM, pcode: SO25, name: Bakool}
  - {country: Somalia, iso3: SOM, pcode: SO22, name: Banadir}
  - {country: Somalia, iso3: SOM, pcode: SO16, name: Bari}
  - {country: Somalia, iso3: SOM, pcode: SO24, name: Bay}
  - {country: Somalia, iso3: SOM, pcode: SO19, name: Galgaduud}
  - {country: Somalia, iso3: SOM, pcode: SO26, name: Gedo}
  - {country: Somalia, iso3: SOM, pcode: SO20, name: Hiraan}
  - {country: Somalia, iso3: SOM, pcode: SO28, name: Lower Juba}
  - {country: Somalia, iso3: SOM, pcode: SO23, name: Lower Shabelle}
  - {country: Somalia, iso3: SOM, pcode: SO27, name: Middle Juba}
  - {country: Somalia, iso3: SOM, pcode: SO21, name: Middle Shabelle}
  - {country: Somalia, iso3: SOM, pcode: SO18, name: Mudug}
  - {country: Somalia, iso3: SOM, pcode: SO17, name: Nugaal}
  - {country: Somalia, iso3: SOM, pcode: SO15, name: Sanaag}
  - {country: Somalia, iso3: SOM, pcode: SO14, name: Sool}
  - {country: Somalia, iso3: SOM, pcode: SO13, name: Togdheer}
  - {country: Somalia, iso3: SOM, pcode: SO12, name: Woqooyi Galbeed}

admin1_name_mappings:
  "ben-gumz": "ET06"
  "PL.Sool": "SO14"
  "PL.Sanag": "SO15"
  "PL.Mudug": "SO18"
  "Sc.Mudug": "SO18"
  "Shabelle dhexe": "SO21"
  "Shabelle hoose": "SO23"
  "Juba dhexe": "SO27"
  "Juba hoose": "SO28"

admin1_name_replacements:
  " urban": ""
  "sud": "south"
  "ouest": "west"
  "est": "east"
  "nord": "north"
  "'": ""
  "/": " "
  ".": " "
  " region": ""

admin1_fuzzy_dont:
  - "nord"
  - "north"
  - "sud"
  - "south"
  - "est"
  - "east"
  - "ouest"
  - "west"
  - "syria"
